### ISSUE TITLE
Best practices for using sudo with Sensu checks? 

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#108]
_From @calebhailey on May 9, 2016 19:27_

_Copied from original issue: sensu/sensu-docs#386_

**Comment by cwjohnston** [comment]
_From @GhostLyrics on May 9, 2016 20:31_

Since I needed to use some checks and metrics which required the use of `sudo` - which was better than adding the `sensu` user to loads and loads of different groups, implicitly granting write permissions to files - I came up with the following snippet for use in `/etc/sudoers.d/sensu`.

```
# allow using only the binary name instead of the full path in check definitions
Defaults:sensu secure_path="/opt/sensu/embedded/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# blindly allow all sensu-install provided checks and metrics which follow the proper naming convention with all possible arguments
sensu ALL=(ALL) NOPASSWD: /opt/sensu/embedded/bin/check*.rb *
sensu ALL=(ALL) NOPASSWD: /opt/sensu/embedded/bin/metrics*.rb *
```

Inspiration for this kind of usage came after reading:
- [Michael W Lucas: Sudo: You're Doing It Wrong, BSDCcan 2014](https://www.bsdcan.org/2014/schedule/attachments/283_2014-04-29%20sudo%20tutorial%20-%20bsdcan%202014.pdf)
- [Stefan Horlacher: Dangerous Sudoers Entries - PART 4: Wildcards](http://blog.csnc.ch/2012/10/dangerous-sudoers-entries-part-4-wildcards/)
- [serverfault: using wildcards for paths in sudoers file](http://serverfault.com/questions/383024/using-wildcards-for-paths-in-sudoers-file)

---

update: This example has been developed with `safe_mode = true` in mind.

**Comment by cwjohnston** [comment]
_From @majormoses on December 19, 2017 0:6_

I generally take minimal and explicit security approach where possible, while the above works it gives way too  much access IMHO. The checks themselves should never be run with sudo itself. It should spawn a subshell to elevate itself and then drop permissions. These commands need to be whitelisted in `/etc/sudoers.d/`. Say you need to remove a particular file you have now granted the use of `rm -Rf /` which would be catastrophic. The best solution is to always give access to the minimal required resources. Rather than directly calling `sudo rm $PATH_TO_FILE_OWNED_BY_ROOT` you should create a shell wrapper called something like `elevates-privs-and-removes-$SOME_FILE` and then allow this command to be executed in sudoers. This prevents argument expansion to be used nefariously. While this is an extreme example it demonstrates the danger of doing so. This is more important when you consider that scripts might allow an `eval` which would allow you to execute arbitrary ruby to create a new script and execute, as you have whitelisted the actual check script this will allow them to carry out a privilege escalation which could have been prevented.

**Comment by cwjohnston** [comment]
_From @majormoses on December 19, 2017 0:15_

A less extreme example would be in the case of auto remediation, if a service is not running the logical thing to do is to attempt to start it. As the process is not likely owned by sensu this will require elevating privileges. While it might be tempting to just whitelist the service commands such as `/usr/bin/sv`, `/usr/bin/service'`, `/usr/sbin/service`, `/bin/systemd`, etc this is not recommended for the same reasons as above. You should create a per service wrapper that allows only starting of the service. This prevents checks from stopping either the intended or otherwise services.

**Comment by cwjohnston** [comment]
_From @majormoses on December 19, 2017 0:18_

> This example has been developed with `safe_mode = true` in mind.

This should honestly be the default as it is terrifying in the context of allowing http apis for check creation, execution, scheduling, etc especially considering that most people do not understand how to properly secure systems.

**Comment by cwjohnston** [comment]
_From @GhostLyrics on December 19, 2017 1:10_

@majormoses I tend to agree with you. What I dislike here is that you assume that everyone will have the additional time for engineering for developing and maintaining such a wrapper for every check that needs it.

**Comment by cwjohnston** [comment]
_From @majormoses on December 19, 2017 1:42_

> What I dislike here is that you assume that everyone will have the additional time for engineering for developing and maintaining such a wrapper for every check that needs it.

I apologize if you felt like I was attacking you, that was not my intention. I used the :heart: emoji showing that I did like the solution. That being said I had a few extra thoughts as a security conscious engineer and based on the topic felt like they needed to be called out.

The title of this article is "Best Practices for using sudo with Sensu checks?" not "The Unfortunate Reality for using sudo with Sensu checks?". As much as I wish that I followed everything I said here, I don't but the goal was to discuss best practices. Even if you are aware of the risks and have accepted them, this is not something I would encourage people to do without explaining the consequences which I outlined. Many I would wager would not have noticed the vulnerabilities pointed out.

**Comment by asachs01** [comment]
@majormoses had mentioned this in #318 , and after some discussion with @cwjohnston we're going to make this aspect its own doc.

**Comment by hillaryfraley** [comment]
Revisit for Sensu Go

**Comment by majormoses** [comment]
I _think_ almost everything here still is the same other than a less consistent path when using assets. That being said I could very easily be missing something as I don't use `sensu-go` yet for real as its not mature enough for my needs.

**Comment by hillaryfraley** [comment]
- [ ] 1. Test how the pattern work for Sensu Go? (pattern in https://github.com/sensu/sensu-docs/issues/108#issuecomment-358735233)
- [ ] 2. Concrete example of a Bonsai asset that needs sudo?
- [ ] 3. Suggest a pattern that works for Sensu Go in the Secure Sensu guide.
- [ ] 4. Update Secure Sensu guide with suggested approach and clarify that complete security with sudo is a deep subject and not in scope for our guide. Add links mentioned in https://github.com/sensu/sensu-docs/issues/108#issuecomment-358735233 to Secure Sensu for further reference.

**Comment by hillaryfraley** [comment]
How can we make sudo work with assets without requiring people to update their sudo every time an asset changes? Work with developer advocates.

**Comment by majormoses** [comment]
I have had years to think about this and I am deeper in security field now than I was before. Unless you abandon all sane operating system protections you are going to need to update something, this is by design. There are multiple ways to accomplish that (without an action) but they all compromise the security of the system at very fundamental levels. For fear that someone actually attempts any of them I won't mention them publicly. You should have to research how to break your OS and should not be encouraged by the Maintainers in a best practices. Automation is always a key component to scale and security. This challenge is the same on every operating system in different forms.

For any asset/check/metric/handler/filter that needs to be privileged, it needs to be configured entirely outside of sensu even if it drops the resource on disk. The of nature of assets have no deterministic path, so it's easier to use the same process to update both at once.

**Comment by majormoses** [comment]
@mattyjones I would love to hear your thoughts if you can spare the time.

**Comment by mattyjones** [comment]
I have nothing concrete except how we did things.

1. **safe-mode** was enabled, end of story
2. I wrapped checks with binstubs to avoid argument trampling, the checks are fairly safe but the reality is we had to secure everything. A malicious user only needs to find one thing.
3. (unrealistic for most people) When possible I ported the ruby checks to Go and in some cases Rust starting in late '14 and used binstubs. This was for security reasons and we had environments where runtimes should not be available.
4. Never use `sudo` w/o a full explicit path
5. Chef and later Git2Console -> Consol Template handled stuff for us. We had baseline binstub templates that got auto-generated by Consul Template based on a JSON blob that had the options/flags we wanted. We add a new check, some simple JSON, and a new binstub got auto-generated. This allowed developers to generate their own app monitoring on the fly with a 1/2 dozen lines of JSON in a git repo, a single file per check to keep it simple.
6. Sudo was against the binstub, on an as-needed basis, again based on a flag in Chef/Consul. It was explicit, allowing only that specific binstub that was already configured with the necessary flags via the above JSON blob. No flags in `ps` so little risk of exposing internal attributes, env variables, etc
7. There were probably a few other things as well, such as running them in isolated environments. etc
8. I slept very well at night.

The point being there are lots of ways to solve this sanely, using automation tools. The tools already know how to write files to disk and configure them. They have baseline templates for everything that can be modified dynamically based on the output of a run. If something needs `sudo`, that fine, it happens...a lot...and *NOPASSWD* is a really bad idea ut it is fine in many environments, just make sure the sensu user and scripts clean all input coming in to them.

I will see if I can dig anything up from then if I get a chance

@majormoses @cwjohnston

**Comment by mattyjones** [comment]
Also some context:
- We started w/ Sensu w/ 0.12 or 0.14?? ~early/mid 2014
- Multi-provider (several on-prem installs, including mac stadium)
- AWS multi-region (APAC, EU, US)
- Mix of containers w/o a runtime and EC2 + bare metal w/ a runtime
- Servers configured headless in round-robin
- ~150 different checks, including custom, on various boxes
- RMQ was clustered and federated
- Redis was HA
- Consul DNS was used for dynamic availability
- Meos/Marathon was used for containers
- Alpine was the default container image.

**Comment by jspaleta** [comment]
Okay here are my notes for what is probably overbroad sudo configuration changes to run sudo for all installed assets for a sensu_agent.

### Note: 
these instructions can be tightened up further by changing the wildcard '**' glob  in the directory paths to be explicit asset directory paths. The asset paths the sha512 sum in the asset definitions, so its possible to explicitly know them, they are not randomly generated uuids. If you want to be as secure as possible, whitelisting the sha512sums you trust seems appropriate to me.

### sudo config: secure_path adjustment
if secure_path is enabled you may want to extend it to include the Sensu asset directories. The benefit of doing this is that you will be able to call the check commands without explicitly setting the path in the call to sudo. 
The difference between `sudo echo "hello world"`  and `sudo /usr/bin/echo "hello world"`  

Very useful for checks that need to run on different hosts and may have different builds for different hosts. 

Example:
```
# Update secure_path to include Sensu assets 
Defaults    secure_path = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/cache/sensu/sensu-agent/**/bin 
```

### sudo config:  allow Sensu agent to run commands as sensu user and keep envvars
```
# Give sensu access to use sudo -E for assets installed under /var/cache/sensu/sensu-agent/
sensu   ALL=(ALL)       NOPASSWD:SETENV: /var/cache/sensu/sensu-agent/**/bin/*.*
sensu   ALL=(ALL)       NOPASSWD:SETENV: /var/cache/sensu/sensu-agent/**/bin/*
```
` NOPASSWD:SETENV:`  allows sensu user to run without a password and allows use of `sudo -E` to ensure environment  

### Sensu check command: preface commands with sudo -E to ensure agent provided envvars are passed into sudo environment

With the above sudo config changes you can prefix _all_ asset provided commands with `sudo -E` and should get expected operation from sensu-agent using default agent configuration settings.

### Note(again for emphasis):  
the `**` and `*` globs in these configuration changes can be replaced with specifics for the assets that you trust to run privileged.   The use of the globs here is provided primarily as a pattern that you can test in a non-production environment. In production you will most likely want to whitelist specific asset sha512sums to replace the `**` globs and perhaps go further and whitelist specific commands to replace the `bin/*.*` and `bin/*` globs

**Comment by majormoses** [comment]
@jspaleta I am not trying to be combative. As Matt and I have said `sudo` should always be explicit in its needs which includes paths, env, etc.

I understand the desire to make it "easy" but that flys in the face of security best practices in this case. There are very good reasons for these decisions and perfectly reasonable solutions with automation. If you have good automation this is an easy problem to solve in a very explicit manner. If you dont want to use "config management" then illustrate a (shell) script that you can pass in reasonable data object and it will output the appropriate files. Use `/etc/sudo.d/my-awesome-check` to store all the options specific to that check. I am happy to give you some example chef code.

Take `NOPASSWD:SETENV` for example not all `sudo` commands need to preserve the environment, preserve it when you need it.

If you want to write an article called "Security Bad Practices" that's totally fine but that's not what this is about, this is about "Best Practices", which will always be explicit and only when needed. If I have to pick a single most important aspect of security, it's the [Principle of Least Privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege). What is being proposed here is nearly the opposite of that.

I have maintained thousands of sensu checks, handlers, and mutators for my orgs and the community. The vast majority of these do not need `sudo` at all. There are always exceptions but we should not pretend they are the rule. Each exception should decide exactly what it needs (preserving the env, path, etc).

To illustrate the danger (and reinforcing Matt's point about input sanitation) I found this perfect example of why this is so dangerous:
- https://github.com/sensu-plugins/sensu-plugins-raid-checks/blob/3.0.0/bin/check-megaraid-sas-status.rb#L39-L43
- https://github.com/sensu-plugins/sensu-plugins-raid-checks/blob/3.0.0/bin/check-megaraid-sas-status.rb#L57

This check would make it possible to execute arbitrary commands outside of the context of sensu and because you have allowed this check to run without guardrails it's a perfect privileged code injection opportunity. This is complete system ownage at this point just by installing it with the config in place. It's in general an incredibly dangerous check and as such its incredibly important that care is taken if you decide to use it.

**Comment by majormoses** [comment]
> the `**` and `*` globs in these configuration changes can be replaced with specifics for the assets that you trust to run privileged. The use of the globs here is provided primarily as a pattern that you can test in a non-production environment. In production you will most likely want to whitelist specific asset sha512sums to replace the ** globs and perhaps go further and whitelist specific commands to replace the `bin/*.*` and `bin/*` globs

I didn't ignore this, its just in my experience not been effective to offer the easy path and then say to be secure you must do hard way, 9/10 folks will choose the easy path. Automation is the easy path that solves both concerns. I think it's also important that if we are in the business of giving specific `sudoers` advice then we need to take on the burden of explaining which options should be used where which is unrealistic. IMO we should not be in this business at all or should be offering the most secure version of it and then let people hack their own systems security to oblivion.

**Comment by hillaryfraley** [comment]
Closing for now -- will create a new docs issue to cover guidance for targeted permissions (see #3034 for more information).
