### ISSUE TITLE
Feature request: be able to generate monolith document (pdf, epub, or mobi) for offline reading

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-docs#1178]
I would like the opportunity to download the documentation for viewing with an offline reading device such as an iPad or a Kindle.
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [X] Feature request

## Expected Behavior

Read without distractions in all the other places I read instead of a browser window.
## Current Behavior

Have to click through the web site to read documentation.
## Steps to Reproduce (for bugs)

1.  Tote laptop to pool, or the bus, or the beach.
2.  Tether laptop to phone (or, if you're lucky, bus WiFi)
3.  Browse documentation as you stare longingly at your purpose built Kindle...

## Context

* Browser(s) and version(s): 
* OS:

**Comment by apaskulin** [comment]
To do: Generate a downloadable EPUB for each version of the docs using Hugo's [Custom Output Formats](https://gohugo.io/templates/output-formats).

**Comment by rnevius** [comment]
@apaskulin Hugo doesn't have built-in support for EPUB...The only [built-in Hugo output format](https://gohugo.io/templates/output-formats#output-format-definitions) that would be [supported by Kindle](https://kdp.amazon.com/en_US/help/topic/G200634390) would be HTML or plain text.

Since the Sensu Docs site – in its current state – relies on JavaScript (including some third-party hosted libraries), I think generating a Kindle/offline-friendly version of the documentation would look something like the following:

1. Write new Hugo layouts that output each required product/platform/version combo as one long HTML page with no JavaScript dependencies. Of course the assembly of this content would be handled by Hugo.
2. Include [HTML Table of Contents](https://kdp.amazon.com/en_US/help/topic/G201605710) in the format required by Amazon/Kindle.
3. Either:
    a. Include a link to the ebook-formatted HTML content with instructions for downloading/archiving/importing the docs to a Kindle (e.g. (1) visit this link, (2) save and archive, (3) upload to your kindle).
    b. Or, at the end of the production build process, add a script that will generate .zip files for each product/platform/version combo and upload those archives to some kind of static file server. Link to these files directly (e.g. click this link to download offline docs for Kindle).

I'm interested in hearing your thoughts about the above.

**Comment by hillaryfraley** [comment]
Completed in https://github.com/sensu/sensu-docs/pull/1802
Offline docs available on supported versions pages (restored to Go docs in https://github.com/sensu/sensu-docs/pull/1820)
