### ISSUE TITLE
Site displays incorrectly in Internet Explorer

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1243]
The home page, navigation sidebar, and fonts display incorrectly in Internet Explorer.

Screenshot using Windows2012R2:

![screen shot 2019-02-26 at 1 35 00 pm](https://user-images.githubusercontent.com/11339965/53449320-65793800-39ce-11e9-8f49-e8b6ed398a9b.png)

Troubleshooting: [Adding the site to compatibility view](https://support.microsoft.com/en-us/help/17472/windows-internet-explorer-11-fix-site-display-problems-compatibility-v) didn't fix the issue.

**Comment by asachs01** [comment]
Ehhhh, are customer still using IE? Do we have any analytic data to go along w/ keeping this open?

**Comment by hillaryfraley** [comment]
@asachs01 I just checked Google Analytics. Since August, here are the browser stats:

1. Chrome 15,730 (68.57%)
2. Firefox 3,327 (14.50%)
3. Safari 1,731 (7.55%)
4. **Internet Explorer 1,163 (5.07%)**
5. Edge 317 (1.38%)
6. Netscape 219 (0.95%)
7. Opera 186(0.81%)
8. UC Browser 99(0.43%)
9. Safari (in-app) 43(0.19%)
10. Samsung Internet 43(0.19%)

**Comment by hillaryfraley** [comment]
We would like to direct IE users to the PDF copy of the docs (posted to https://docs.sensu.io/sensu-go/latest/getting-started/versions/).

@hillaryfraley update sensu-docs repo readme to add link to latest PDF and note that we are not supporting the docs site for IE.
