### ISSUE TITLE
Redact string missing space between values

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#1347]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [X] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior
Example values for attributes are valid.

## Current Behavior
The example redact value in the agent reference guide is not value. Sensu Go will not properly parse the values to be redacted. 

https://docs.sensu.io/sensu-go/5.3/reference/agent/#security-configuration-flags

This:

```
redact: "secure-key,secure-password"
```
Should be:

```
redact: "secure-key, secure-password"
```

## Possible Solution
- [ ] Fix the issue described above
- [ ] Find other occurrences of this problem as other attributes may take comma delimited lists of strings.

**Comment by apaskulin** [comment]
In my testing, I observed that the following syntax, in an agent.yml config file:

```
redact: "password, passwd, pass, api_key, api_token, access_key, secret_key, private_key, secret"
```  

produced extra commas within the strings in the resulting entity definition:

```
redact:
  - password,
  - passwd,
  - pass,
  - api_key,
  - api_token,
  - access_key,
  - secret_key,
  - private_key,
  - secret
```

Using the list format in the agent.yml file resulted in the same syntax in the entity definition:

```
redact:
  - password
  - passwd
  - pass
  - api_key
  - api_token
  - access_key
  - secret_key
  - private_key
  - secret
```

@rgeniesse Is this consistent with what you observed?

**Comment by rgeniesse** [comment]
@apaskulin that is my experience as well. Redaction still works on each string in the list, so I don't know if it has other implications or why the default list behaves differently in not showing the `,`. 

Functionally it looks fine to me, but may warrant a quick Eng question.

**Comment by apaskulin** [comment]
I think the underlying issue here is that `redact`, among others, is a string slice.

String slice attributes in backend config:

- EtcdAdvertiseClientURLs
- EtcdListenClientURLs
- EtcdListenPeerURLs
- EtcdInitialAdvertisePeerURLs

String slice attributes in agent config:

- BackendURL
- Redact
- StatsdEventHandlers
- subscriptions

To do:

- [ ] In the backend and agent references, change the type to "String slice" for the attributes listed above.
- [ ] Correct the config file examples for those attributes to use the list format in the reference docs and example config files both in the docs and within Sensu packages.
- [x] Test the behavior of some of these string slice attributes using `sensu-agent start` command flags. Current examples show a comma-separated list without spaces: `--subscriptions disk-checks,process-checks`

@rgeniesse I can do those first two to-do items. Would you be able to look into the third?

**Comment by rgeniesse** [comment]
@apaskulin. I can take a look at item 3.

**Comment by rgeniesse** [comment]
All tested against 5.5 agent, backend and sensuctl.

`sensu-agent start --subscriptions disk-checks, process-checks` results in (space):

```
    "subscriptions": [
      "disk-checks",
      "",
      "entity:sensu-centos"
    ],
```

`sensu-agent start --subscriptions disk-checks,process-checks` results in (no space):

```
    "subscriptions": [
      "disk-checks",
      "process-checks",
      "entity:sensu-centos"
    ],
```

So for `--subscriptions`, appears to be a requirement to not have a space.

`sensu-agent start --redact secure-key,secure-password` results in (no space):

```
    "redact": [
      "secure-key",
      "secure-password"
    ],
```

`sensu-agent start --redact secure-key, secure-password` results in (space):

```
    "redact": [
      "secure-key",
      ""
    ],
```

So for command line `--redact`, no space is required, which goes against the space requirement in `agent.yml`.

`--statsd-event-handlers` wasn't able to test as it doesn't show up in the detailed entity view of sensuctl. Not sure how to test this.
