### ISSUE TITLE
Docs Feedback

### ISSUE THREAD

**Issue by spykermj** [sensu/sensu-docs#1348]
Link to page: 

https://docs.sensu.io/sensu-go/5.4/reference/agent/#creating-a-dead-man-s-switch

I'm not sure if it is a bug in the documentation or a bug in sensu go, but it definitely doesn't work.

If it is a bug in the sensu go agent, I've filed a bug here:

https://github.com/sensu/sensu-go/issues/2858

If you could help move it along that would be great. If it is a bug in the documentation because the feature was withdrawn, this is a big impediment to migrating to sensu go as it is quite an important feature.

**Comment by apaskulin** [comment]
Hi @spykermj, thanks for submitting this feedback. My apologies for the confusion here. You are correct, the examples shown in https://docs.sensu.io/sensu-go/5.4/reference/agent/#creating-a-dead-man-s-switch do not work because the agent socket ignores all attributes that aren't listed in the [socket event specification](https://docs.sensu.io/sensu-go/5.4/reference/agent/#socket-event-specification). You can still use the `ttl` attribute with your Sensu checks, just not as part of an agent socket event payload.

In the short term, I'll remedy this in the docs by removing that section and commenting on sensu/sensu-go#2858 with some additional context. Thanks again for finding this and submitting the bug report!

**Comment by apaskulin** [comment]
Hi @spykermj, I wanted to let you know that the dead man's switch feature is available using the Sensu agent API. Check out the documentation here: https://docs.sensu.io/sensu-go/5.7/reference/agent/#detecting-silent-failures Let me know if you have any questions!

**Comment by spykermj** [comment]
Thanks, if we migrate to sensu go, I'll just change over to using the http
api rather than the tcp socket api.
