### ISSUE TITLE
Search is not returning any results

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#1459]
Currently, Algolia isn't returning any search results. We're assuming that this regression is a result of #1446. We've confirmed that this isn't an Algolia outage. @rnevius

Algolia DocSearch reference: https://community.algolia.com/docsearch/dropdown.html
Algolia Index: https://github.com/algolia/docsearch-configs/blob/master/configs/sensu.json

**Comment by rnevius** [comment]
~This is definitely not related to #1446 or #1439. I have rolled back to an [earlier commit](https://github.com/sensu/sensu-docs/commit/ab10bfb3a0800288f582e20b5c6036ce18da4032) locally, and the problem persists.~

While the Algolia service isn't down, I suspect there is an issue with their Sensu index. Evidence of this is that results _do_ appear if `facetFilters` are removed from `algoliaOptions` when instantiating the `docsearch`.

EDIT: This may be due to the [version selector](https://github.com/algolia/docsearch-configs/blob/master/configs/sensu.json#L53) in the Algolia Index config. PR incoming.

**Comment by rnevius** [comment]
This is the relevant line from the [docsearch config](https://github.com/sensu/sensu-docs/blob/master/layouts/partials/footer_js.html#L177), for providing to Algolia support:

```javascript
algoliaOptions: { 'facetFilters': [['tags:sensu-go','tags:plugins', 'tags:sensu-core', 'tags:sensu-enterprise', 'tags:sensu-enterprise-dashboard', 'tags:uchiwa'], ['version:5.7','version:1.0','version:2.15','version:1.7','version:3.4']]},
```

**Comment by rnevius** [comment]
I have submitted a PR for this, but really think that this should be a temporary workaround. I'm not an Algolia doc search expert, but as far as I can tell, using `start_url` regular expressions is a better idea moving forward, so that the version isn't tied to this specific markup. Here's the relevant section in the docs: https://community.algolia.com/docsearch/config-file.html#using-regular-expressions

**Comment by apaskulin** [comment]
This bug was resolved by https://github.com/algolia/docsearch-configs/commit/c46053f359ac210572ebae66ea7b06fab1c6ac75, so I'm closing this issue for now. But we'll revisit the `start_url` if we run into further issues.
