### ISSUE TITLE
stashes API examples are misleading w.r.t. sensu-admin

### ISSUE THREAD

**Issue by petere** [sensu/sensu-docs#153]
Consider this example in the stashes API:
```json
{
    "path": "silence/i-424242/chef_client_process",
    "content": {
        "timestamp": 1383441836
    },
    "expire": 3600
}
```

Obviously, you can put whatever you want in a stash, but someone who will naively try the above might be confused that sensu-admin isn't going to do anything with the data.  An actual working example would be

```json
{
    "path": "silence/i-424242/chef_client_process",
    "description": "a bit broken right now",
    "timestamp": 1383441836,
    "expire_at": "2013-11-02T22:23:56-0400"
}
```

Would it be useful to update the stashes documentation in general to reflect what sensu-admin expects?

**Comment by cbake6807** [comment]
Umm, +10 ?

**Comment by calebhailey** [comment]
Closing this issue because sensu-admin is no longer being maintained (in favor of [Uchiwa](github.com/sensu/uchiwa) or the [Sensu Enterprise](https://sensuapp.org/sensu-enterprise) Dashboard). 

Having said that, stashes documentation has _never_ been very good, and we're planning on improving them in the 0.23 docs.
