### ISSUE TITLE
Redirect to 4xx error

### ISSUE THREAD

**Issue by bananabele** [sensu/sensu-docs#1837]
Link to page: https://docs.sensu.io/sensu-go/latest/guides/create-a-ready-only-user

### Feedback
This page is redirecting to a 4xx error -- I'm guessing it should redirect here? https://docs.sensu.io/sensu-go/5.14/guides/create-read-only-user/#how-to-create-a-read-only-user

**Comment by hillaryfraley** [comment]
@cwjohnston I talked to Anna about this one because I couldn't find the https://docs.sensu.io/sensu-go/latest/guides/create-a-ready-only-user link in our docs. She said:

"so from what I can tell, it's not that it's necessarily still linked somewhere, but that it was removed without there being a proper redirect
so that url had been out and about in the wild and now it's not; instead of redirecting, it just goes to 404
I think creating a redirect for that url to the new one (that jumps to the spot on the page) should solve it"
