### ISSUE TITLE
Create "latest" metalink to always point to latest released Sensu Go version

### ISSUE THREAD

**Issue by toozej** [sensu/sensu-docs#1845]
Create "latest" metalink to always point to latest released Sensu Go version, similar to the [Ansible Docs site](https://docs.ansible.com/ansible/latest/). For example: for Sensu Go version 5.14, https://docs.sensu.io/sensu-go/latest/sensuctl/reference/ would redirect to https://docs.sensu.io/sensu-go/5.14/sensuctl/reference/, but when version 5.15 is released, "latest" would point to version 5.15.

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [x] Enhancement (add new site functionality)

## Expected Behavior

meta-link "latest" (as in https://docs.sensu.io/sensu-go/latest/$topic) where "latest" always points to the latest released version of Sensu Go. 

## Current Behavior

No "latest" link exists, so bookmarked or linked documentation pages are quite often out of date, requiring the user to use the drop-down version menu to change to the current version of the documentation. 

## Possible Solution

Redirect either in web-server layer, or using static site generator (Hugo?)

## Steps to Reproduce (for bugs)
N/A

## Screenshots (if appropriate):

Example of Ansible documentation site:
![Screenshot from 2019-10-12 11-58-17](https://user-images.githubusercontent.com/1201223/66706485-f693e980-ece7-11e9-8b3d-dc987db60175.png)

Current Sensu Go documentation page version drop-downs:
![Screenshot from 2019-10-12 11-58-35](https://user-images.githubusercontent.com/1201223/66706484-eda31800-ece7-11e9-8108-d44ef972f254.png)

## Context

Makes keeping bookmarks/lists of latest-version commonly referenced documentation links easier, utilizing the version drop-down less. 

* Browser(s) and version(s): Chrome (but should work for all browsers)
* OS: Linux (but should work for all OSes)

**Comment by hillaryfraley** [comment]
@toozej , thank you for creating this issue!

You can manually create bookmarks that use `/latest`, although we have some work to do on our side to make sure the URL doesn't change when the page loads in the browser.

For example, if you bookmark https://docs.sensu.io/sensu-go/latest, it will always load the docs for the latest Sensu Go release. However, when the page loads in your browser, the URL will automatically update to https://docs.sensu.io/sensu-go/5.14/ (because 5.14 is currently the latest release number).

We are also considering your suggestion for including "latest" in the dropdown menu for selecting a docs version.

Thanks again! We appreciate you for taking the time to help us improve Sensu documentation.
