### ISSUE TITLE
sensuctl command examples don't work

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-docs#2014]
The examples given for using `sensuctl command` don't work as provided.

Additionally, some clarification is needed.  Is using sensu-email-handler a good example in the first place?  If the command being ran is mapped to the bin/entrypoint for the asset then that file doesn't even exist in that asset.  As well, it's meant as a pipe handler, expecting to read from STDIN, can you do that with `sensuctl command exec`?
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [X] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Current Behavior

Copy/Paste of the provided example of sensu-email-handler doesn't work.  It does appear to get further without the parentheses.  The failure after that may or may not be an actual issue with Bonsai integration.
```
[vagrant@backend ~]$ sensuctl command install sensu-email-handler (sensu/sensu-email-handler:0.2.0)
-bash: syntax error near unexpected token `('
[vagrant@backend ~]$ sensuctl command install sensu-email-handler sensu/sensu-email-handler:0.2.0
fetching bonsai asset: sensu/sensu-email-handler:0.2.0
Error: one or more asset builds are required
```
## Affected Docs Pages

[Extend sensuctl with commands](https://docs.sensu.io/sensu-go/5.15/sensuctl/reference/#extend-sensuctl-with-commands)
## Steps to Reproduce (for bugs)

1.
2.
3.

## Context

* Browser(s) and version(s): 
* OS:

**Comment by jspaleta** [comment]
More on this.
The sensu-email-handler examples needs to be removed entirely.
The sensuctl command concept requires a specially packaged asset with a specially named binary

It is not a general command runner... handler assets won't work.

Here's how I tested.

1) instead sensu-email-handler with explict url and checksum
`sensu-email-handler --url https://assets.bonsai.sensu.io/45eaac0851501a19475a94016a4f8f9688a280f6/sensu-email-handler_0.2.0_linux_amd64.tar.gz  --checksum  d69df76612b74acd64aef8eed2ae10d985f6073f9b014c8115b7896ed86786128c20249fd370f30672bf9a11b041a99adb05e3a23342d3ad80d0c346ec23a946`

2) attempted to exec
`sensuctl command exec sensu-email-handler`

3)result in error: no entrypoint defined
`INFO[0000] asset includes builds, using builds instead of asset  asset=sensu-email-handler component=asset-manager entity=sensuctl
sh: entrypoint: command not found`

**Comment by jspaleta** [comment]
I don't think we have an existing example of a sensuctl command asset in bonsai yet, which makes getting the documentation for bonsai integration working sort of a chicken and egg problem.

Assuming we had an example called sensu/sensuctl-fun-time-command in Bonsai

the syntax would look something like this
`sensuctl asset add sensu/sensuctl-fun-time-command:X.Y.Z`

The parenthesizes in the usage message for `sensuctl command install --help` are a syntax to denote mutually exclusive arguments and are not required in the actual call.
