### ISSUE TITLE
Guide Wanted: Scaling Sensu

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#228]
We've been promising that a guide on scaling Sensu is ["coming soon"](https://sensuapp.org/docs/latest/installation/summary.html#scaling-sensu) for a long time now. We should make good on this.

I've found an older guide to Sensu scalability in the legacy documentation, e.g.: https://github.com/sensu/sensu-docs/blob/master/legacy/0.16/scaling_strategies.md

I think we ought to use this document as the basis of an improved guide.

**Comment by asachs01** [comment]
Base on the team conversation today, I'm rescoping the original PR in #324 so that it's not so broad. That said, there will be several new docs:

- [x] Scaling overview (will include the scaling strategies discussed in the article ^ ) (covered by #565)
- [ ] Knowing when to scale Sensu components
- [ ] Scaling Sensu at Multiple Sites: Isolated Clusters Aggregated by Uchiwa 
- [ ] Scaling Sensu at Multiple Sites: Centralized Sensu and Distributed RabbitMQ
- [ ] Scaling Sensu at Multiple Sites: Centralized Sensu and Directly Connected Clients

Each of the last 3 guides will feature more in-depth discussions of their respective topologies
