### ISSUE TITLE
Document breaking agent contract for 6.0 entity configuration

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#2597]
### Description
See https://github.com/sensu/sensu-go/blob/master/CHANGELOG.md#breaking:
> After initial creation, sensu-agent entity configuration cannot be changed
by modifying the agent's configuration file.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
I'm not sure what the entire scope is, but we'll probably need notes about agent config and websocket contracts.

### Additional context
- https://github.com/sensu/sensu-go/commit/c3914d6787dccd0c68a729bb9dc835c0952f557a
- [Proposal: Agent Entity Backend API Management](https://docs.google.com/document/d/1LhuWC-WUswrUigzKOqsNZrBT5sTdKhvpXlpcUFfF5DE/edit#heading=h.letafivq6wet)

cc @echlebek

**Comment by nikkictl** [comment]
To maintain 5.x agent.yml behavior where the config file is the "source of truth," users may instead choose to create ephemeral agent entities (ex. `deregister: true`). The `deregister` field must be set _before_ the agent entity is created. Keepalive monitoring is not supported for ephemeral entities.

**Comment by hillaryfraley** [comment]
@nikkictl @echlebek I'm having trouble distinguishing whether this info is helpful for users who are installing Sensu for the first time at version 6.0 and or for users who will upgrade from 5.x to 6.0. Or a bit of both.

**Comment by echlebek** [comment]
We'll need to document the entity lifecycle for everyone. There are two paths here.

Path 1 (agent entity)
1. An agent connects to a backend, and its entity definition is created from the information present in `agent.yml`.
2. The entity can be modified via `sensuctl`, the web ui, or the HTTP API.
3. The entity cannot be modified with agent.yml
4. If the entity is deleted, it will revert to the agent's original configuration, from agent.yml.
5. If the entity's class is changed to "proxy", the backend will revert the change so that it is "agent".

Path 2 (proxy entity)
1. A user creates a proxy entity via normal means.
2. The entity can be updated or deleted via normal means.
3. If a user starts an agent with the same name as the proxy entity, its class will change to "agent" and its "system" field will be updated by information from the agent.

**Comment by hillaryfraley** [comment]
@echlebek for proxy entities, when you say "The entity can be updated or deleted via normal means." what are the normal means? Do you mean via sensuctl, the web UI, and the entities API?
