### ISSUE TITLE
Document password protecting Redis

### ISSUE THREAD

**Issue by AirCombat** [sensu/sensu-docs#377]
I tried configuring RequirePassword in redis.conf and added the password to my sensu's redis.json unsuccessfully.

Some documentation on this would be helpful.

**Comment by calebhailey** [comment]
Redis password authentication is documented in the Redis reference docs, here: https://sensuapp.org/docs/0.25/reference/redis.html#redis-attributes 

Additional configuration details were also added to the Redis installation guide, here: https://sensuapp.org/docs/0.24/installation/install-redis-on-ubuntu-debian.html 

I'm going to close this due to inactivity (mostly on our part). If this is still unclear, please feel free to open a new issue. :)
