### ISSUE TITLE
Need guide describing running your own catalog server

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#3907]
### Description

As a Sensu operator who requires a high level of control over the specific integrations offered through the catalog, I'd like to have a guide describing how to run my own catalog server with curated integrations

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [x] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

**Comment by jspaleta** [comment]
Prior to this we need to add documentation for the GlobalConfig resource to describe the spec attributes and update the API reference to list catalog in the api examples.
https://docs.sensu.io/sensu-go/latest/api/enterprise/webconfig/#configglobalconfig-get

We don't have a GlobalConfig resource reference at present that provides detailed descriptions of the resource specification. Its going to be difficult to talk about using a custom catalog if we can't point people to the GlobalConfig reference that describes what the available configuration settings do.

**Comment by hillaryfraley** [comment]
I'm a bit out of the loop because I thought this was not available for customer use yet. I'll find the code PR to figure out the Catalog attributes in GlobalConfig so I can update the enterprise/web/v1 API doc that Jef linked.

@jspaleta when you say that we need a GlobalConfig resource reference, are you talking about something different than the reference we have here: https://docs.sensu.io/sensu-go/latest/web-ui/webconfig-reference/? Or do you mean that we need to update the GlobalConfig reference to include the attributes for configuring the Catalog?

**Comment by jspaleta** [comment]
> @jspaleta when you say that we need a GlobalConfig resource reference, are you talking about something different than the reference we have here: https://docs.sensu.io/sensu-go/latest/web-ui/webconfig-reference/? Or do you mean that we need to update the GlobalConfig reference to include the attributes for configuring the Catalog?


That reference is misssing spec attributes that control the catalog location.  Before we can talk about setting up a private catalog we need to get that spec updated to included the relevant attributes.

**Comment by hillaryfraley** [comment]
I see, yes the spec is missing that info. I can add it when we're ready to document this.

https://sumologic.slack.com/archives/C02ANQE1G2Y/p1655323147260659

**Comment by jspaleta** [comment]
Honestly I sort of need to reference that webui config in the block post I'm writing show how to do local integration development using the catalog.

**Comment by hillaryfraley** [comment]
Ahh OK. Did DA meet with the customer to walk them through a local catalog? I ask because the slack discussion I linked sounds like that's what is blocking the decision about whether this is supported ("Perhaps we can collect some feedback based on their experience and then decide if we're ready to make it a supported feature by documenting it.")

A possibility: document it as we have BSM and prune (`<feature> is an alpha feature and may include breaking changes.`).

I'm wary of updating the GlobalConfig reference alone without adding a catalog API doc and a guide to explain the feature and provide context for all the stuff in the GlobalConfig reference.

**Comment by jspaleta** [comment]
I think a dedicated reference for GlobalConfig would be very useful, but keeping some of its attributes officially undocumented at this point is a blocker for producing additional higher level content. 

For example, anything I produce to document catalog integration contribution will reference the undocumented attributes so the contributor can do a full local test of the integration using the workshop env.

Even if we aren't ready to document and support a private catalog with customers, GlobalConfig needs to be documented as a reference before we can realistically write that guidance when we are ready.

**Comment by hillaryfraley** [comment]
Confirmed not ready to document: https://sumologic.slack.com/archives/C0254420A1Y/p1656601380581059

**Comment by hillaryfraley** [comment]
https://github.com/sensu/sensu-enterprise-go/issues/2332#issuecomment-1258464733
