### ISSUE TITLE
document env vars presented to check context

### ISSUE THREAD

**Issue by agoddard** [sensu/sensu-docs#3909]
when checks are run, we modify $PATH to include runtime asset paths, as well as adding library paths and paths to the root directories of runtime assets, in some cases these are useful for working around environment changes outside of sensu, such as sudoers config. It would be helpful to document these somewhere so as to allow people to understand when they might need to make use of the env vars in checks (for example, when `secure_path` sudo config removes the asset bin directories from `PATH`

**Comment by hillaryfraley** [comment]
I think we already have these documented (the pattern is documented):
https://docs.sensu.io/sensu-go/latest/plugins/assets/#environment-variables-for-dynamic-runtime-asset-paths

Maybe there is some explanation missing that could make this info more helpful or more complete.

edit: The documented pattern might be incomplete. I believe the environment variable would also include the namespace (see https://docs.sensu.io/sensu-go/latest/sensuctl/sensuctl-bonsai/#install-dynamic-runtime-asset-definitions), so in the documented example, the env var should be `SENSU_SENSU_WINDOWS_POWERSHELL_CHECKS_PATH ` (two `SENSU` to accommodate the namespace) instead of `SENSU_WINDOWS_POWERSHELL_CHECKS_PATH ` (one `SENSU`). I need to confirm this.

edit2: The documented pattern also only includes an example for Windows agents. Should we also provide an example for Ubuntu and CentOS agents?

**Comment by lrosenman** [comment]
absolutely include the Linux/Unix agents -- It's what caused me to ask for this.

**Comment by lrosenman** [comment]
and yes, it includes the namespace (I.E. sensu/sensu_windows_powershell_checks -> SENSU_SENSU_WINDOWS_POWERSHELL_CHECKS_PATH

This drove me crazy for a while.
