### ISSUE TITLE
RHEL Platform: Cut and paste of Yum repository instructions create malformed repo config.

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-docs#391]
## This is an issue with:

- [x] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)

## Expected Behavior

cut and paste of the echo command to generate sensu.repo file should result in a valid repo file.

## Current Behavior

Problem:
The highlight markdown for the shell instructions introduce leading whitespace into the configuration file when the multiline echo command is cut and pasted.  Subsequently yum/dnf fails to see it as a valid file.   

## Possible Solution

Option 1: Replace the echo instructions with a one line wget for the repo file as a small downloadable artifact hosted by sensu.
Option 2:  Can the markdown styling be adjusted to prevent the leading white spacing for the shell command highlight box?  

## Steps to Reproduce (for bugs)

1. cut and paste the echo command from 
https://docs.sensu.io/sensu-core/1.3/platforms/sensu-on-rhel-centos/#install-sensu-core-repository

2.  yum list sensu -> yum will throw an error message about sensu.repo being unloadable

3.  Edit sensu.repo and remove all leading whitespace on configs lines

4. yum list sensu   -> now works

## Context

Somewhat of a head scratcher stumbling block for installation of sensu core.  Yum's error isn't very helpful as to why the repo file is not valid. It would be great if the cut and paste would just work on CentOS/RHEL.

* Browser(s) and version(s): 
* OS:

**Comment by asachs01** [comment]
Hi @jspaleta ! Good catch on this one! I think it may actually be a rendering issue rather than a content issue. If you take a look at the raw file https://raw.githubusercontent.com/sensu/sensu-docs/master/content/sensu-core/1.3/platforms/sensu-on-rhel-centos.md, the whitespace isn't there (if I'm understanding correctly). Maybe we can get some eyes from @dabria or @sinthetix to confirm? We might just need to change how the code blocks or rendered. Additionally, I wonder if a "copy this text" button wouldn't make things easier :thinking:

**Comment by jspaleta** [comment]
@asachs01 , yeah prob rendering issue.  If this is happening to other code blocks its probably worth fixing as a rendering style.

**Comment by jspaleta** [comment]
interesting.. a similar code block in the quick start guide renders as expected..with no extra spacing when you cut and paste.

Correct behavior example:
https://docs.sensu.io/sensu-core/1.4/quick-start/client-installation/#sensu-core

**Comment by cwjohnston** [comment]
@jspaleta thanks for bringing this to our attention. I'm inclined to treat this immediate issue as a styling bug, so I've updated your original issue posting to reflect that.

I do think we should try to simplify the instructions to a one-line command like you have suggested, but I think it will prove more nuanced than providing a set of static repository definitions. I'll open a separate issue to track this aspect.

@dabria any idea how we can address the introduction of whitespace when we copy and paste from this content? Since this behavior isn't present in every syntax highlighted section, I'm sure there are other places folks are experiencing extraneous whitespace issues.

**Comment by asachs01** [comment]
@dabria @cwjohnston an idea: how about implementing a copy/paste button wherever there are code blocks? Save the end user some headache and just copy it straight w/out having to worry about the highlight/copy/paste issue.

**Comment by cwjohnston** [comment]
We've recently changed some of the display CSS/JS for code blocks, may have had an impact on this behavior. @apaskulin to test if this is still occuring

**Comment by dabria** [comment]
If a copy button is desired I can certainly look into the logistics of it. I'm curious if it might still present a the same problem if the content is rendered a certain way though.

**Comment by apaskulin** [comment]
Good news! This is happening because of extra spaces in the markdown:

```
   {{< highlight shell >}}
   sudo yum install sensu{{< /highlight >}}
```

instead of 

```
   {{< highlight shell >}}
sudo yum install sensu{{< /highlight >}}
```

Going through now to fix these up. Also +1 to a copy button!
