### ISSUE TITLE
Clarify `publish` check attribute

### ISSUE THREAD

**Issue by nhooey** [sensu/sensu-docs#391]
When a `standalone` check is configured, the client is being relied upon to run and manually report results for that check, rather than scheduling a check run.

Since `command` is always required (which seems silly), and `interval` is required when `publish` is omitted, the documentation for a standalone check should mention that setting `standlone: True` implies that `publish: False` should also be set, so `interval` can be omitted, thereby avoiding scheduling of a check.

You could of course make a check standalone, and also schedule it, but mentioning `publish` would help new users.

**Comment by cwjohnston** [comment]
I think the original description of this issue is a bit misleading. Here's my understanding:

1. when `standalone` is true, the check is scheduled by the client. as a result the value of `publish` has no effect
2. when `standalone` is false (default),  the check is scheduled by the server. the value of `publish` indicates whether or not the server should publish check execution requests at the specified interval
3. the intent of the check `publish` attribute is to make checks available for ad-hoc execution via the `/request` API without requiring any automatic scheduling by the server

I think we should make this more clear in describing standalone check definitions, but theres no need for `publish` to be explicitly set to `false` when configuring such definitions.

**Comment by cwjohnston** [comment]
We should enhance the [current description of standalone checks](https://sensuapp.org/docs/0.28/reference/checks.html#standalone-checks) to mention that 

1. `standalone` overrides `subscriptions`
1. `publish` set to `false` on standalone checks prevents checks from being scheduled by the client

We need to adapt the description of `publish` in our check attribute reference to indicate that setting a value of `false`

1. on pubsub checks, prevents server from publishing check requests
2. on standalone checks, prevents clients from scheduling the check

**Comment by cwjohnston** [comment]
This issue was moved to sensu/sensu-docs-site#109
