### ISSUE TITLE
Error installing sensuctl using zsh

### ISSUE THREAD

**Issue by richburroughs** [sensu/sensu-docs#425]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [x] Errata (fix needed for doc content)
- [ ] New content (guide wanted)

## Current Behavior

I tried to install sensuctl for 2.0 per the docs and got this error:
```
curl -LO https://storage.googleapis.com/sensu-binaries/$\(curl -s https://storage.googleapis.com/sensu-binaries/latest.txt\)/darwin/amd64/sensuctl
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to sensu-binaries/latest.txt)/darwin/amd64/sensuctl.</Details></Error>%
```
I'm on macOS High Sierra.

I was able to look at that latest.txt and get that version number, and then plug it in manually. It worked then.

## Steps to Reproduce (for bugs)

1. curl -LO https://storage.googleapis.com/sensu-binaries/$\(curl -s https://storage.googleapis.com/sensu-binaries/latest.txt\)/darwin/amd64/sensuctl

## Context

* Browser(s) and version(s): 
* OS:

**Comment by richburroughs** [comment]
These both work:

```
curl -s https://storage.googleapis.com/sensu-binaries/latest.txt
2.0.0-beta.1-2                                                         
```

```
curl -LO https://storage.googleapis.com/sensu-binaries/2.0.0-beta.1-2/darwin/amd64/sensuctl
```

**Comment by obfuscurity** [comment]
@richburroughs Hmm, the command works fine for me (Windows 10, git shell). Is the problem repeatable on your end?

**Comment by obfuscurity** [comment]
Note to self, if this is indeed a problem, we should reopen under sensu/sensu-go since this is likely some sort of weird permissions thing with the object hosted on GCP.

**Comment by richburroughs** [comment]
@obfuscurity Yeah I was able to repeat it before I opened the issue. But I use zsh. I just tried it with bash and it works fine that way. So it looks like it's just a shell thing.

When I do it with zsh and it fails I also end up with a file on my filesystem called:

$(curl

**Comment by obfuscurity** [comment]
Cool, thanks for the details. We'll leave the issue here since it does appear to be a documentation-specific bug regarding the command.

**Comment by richburroughs** [comment]
Ok.

I also just tried this on another zsh on a CentOS VM with no config at all and it worked fine. So this may be something even more specific to my setup.

**Comment by obfuscurity** [comment]
@richburroughs Can you leave us more specifics here wrt your OS and shell versions (and anything else you can think of that might be relevant)? TIA.

**Comment by richburroughs** [comment]
@obfuscurity Yeah. I'm on macOS High Sierra and the latest iTerm2.

I use zsh from Homebrew, it's at version 5.5.1.

I use this thing called zplug that's kind of a pre-processor for your zsh config so it doesn't take as long to load, along with oh-my-zsh. 

I'll attach my .zshrc. Had to rename it to a text file for Github to take it.

[zshrc.txt](https://github.com/sensu/sensu-docs/files/2009674/zshrc.txt)

**Comment by obfuscurity** [comment]
@richburroughs It works fine for me in High Sierra + iTerm2 + zsh, so it sounds like something specific to your setup. I'm going to close this but if anyone else reports a similar issue we'll definitely look into it further.

**Comment by richburroughs** [comment]
@obfuscurity Sounds good :)

**Comment by richburroughs** [comment]
@portertech Hey we talked about this at Monitorama and you said you've run into it too. I think you had a plan for how to fix it?

**Comment by cwjohnston** [comment]
I believe the problem here is in escaping the subshell (`$\()` vs `$()`) 

This fails in both bash and zsh: `curl -LO https://storage.googleapis.com/sensu-binaries/$\(curl -s https://storage.googleapis.com/sensu-binaries/latest.txt\)/darwin/amd64/sensuctl`

This works in both bash and zsh: `curl -LO https://storage.googleapis.com/sensu-binaries/$(curl -s https://storage.googleapis.com/sensu-binaries/latest.txt)/darwin/amd64/sensuctl`

Note the lack of `\` escaping `(` and `)` in the latter invocation.

As of the [current commit in master](https://github.com/sensu/sensu-docs/blob/3ab7d279c015fdf8c33f2d58f9e132535f6c8cb6/content/sensu-core/2.0/getting-started/installation-and-configuration.md) the command does not show this escaping of the subshell parenthetical, nor do I see it reflected when I copy and paste the command from the live documentation in my browser. As such, I cannot reproduce this and will close the issue.
