### ISSUE TITLE
Use Sensu-Enterprise replace Nagios

### ISSUE THREAD

**Issue by wang1219** [sensu/sensu-docs#440]
I want use Sensu Enterprise replace Nagios, but unlike Nagios maintenance state. If I do not Pagerduty, what a good solution?

**Comment by cwjohnston** [comment]
Hi @wang1219, I'm not 100% sure how to parse your question so I apologize if I misunderstand what you are asking.

I think you are asking how you can schedule maintenance windows, i.e. time periods where all alerts are suppressed without relying on the capabilities of a notification service like Pagerduty. I believe there are two different methods you can try, both of which require Sensu version >= 0.26 or Sensu Enterprise version >= 2.0 (coming soon).

1. You can make use of the new [`/silenced` API](https://cwj.ngrok.io/docs/0.26/reference/silencing.html) to silence relevant subscription/check combinations, optionally using the `expire` attribute to ensure the silencing entries are removed after a given period of time.

1. You can make use of the [`when` attribute](https://sensuapp.org/docs/0.26/reference/filters.html#when-attributes) in a filter defintion, and configure the filter to match subscription and/or check in question during time windows you specify.

In my opinion, using the `/silenced` API is preferable. By comparison the filter option is easier to forget about, as that configuration isn't really bubbled up to Uchiwa or the Sensu Enterprise Console. 

Note that the silencing approach lacks the ability to specify a start or end in wallclock time. This means you need to create the silencing entries manually at the beginning of your maintenance window. Although this isn't quite the same as configuring maintenance windows in advance, my experience has been that it is painful to have maintenance state end while one is still performing maintenance due to underestimating the time required.

**Comment by wang1219** [comment]
@cwjohnston thank you.
