### ISSUE TITLE
Remove URLs from per-platform installation instructions

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-docs#532]
Updated installation documentation for Solaris, AIX, Windows etc to use packages that are available. Platforms that we no longer support should be removed.

**Comment by amdprophet** [comment]
The platforms that we're no longer building packages for are Debian (armhf & powerpc architectures), and Solaris 10 (sparc architecture).

**Comment by cwjohnston** [comment]
To clarify, I think the issue here is that we have a downloads page with links to the latest packages for each platform, and we duplicate those download links on each platform page. This creates duplication as each platform page needs to be updated individually.

Currently Solaris, AIX and other platforms link to non-existent 0.28.0 packages.

IMO the platform-specific pages should only link to [Sensu Downloads](https://sensuapp.org/downloads) and not provide `wget` instructions with a URL as we are doing presently. 

Relates to https://github.com/sensu/sensu/issues/1624
