### ISSUE TITLE
Determine if Erlang R16 should be dropped from supported list

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#578]
A number of issues have been opened recently around using Sensu 0.27 (with openssl 1.0.2) and later with Erlang R16 when SSL is enabled. 

We need to determine if R16 is still supportable with newer OpenSSL in Sensu 0.27 and later.

**Comment by cwjohnston** [comment]
Per https://www.rabbitmq.com/which-erlang.html, Erlang R17 or later is required for reliable TLS/SSL support.

**Comment by agoddard** [comment]
@cwjohnston 👍  I'm in favor of increasing the minimum supported version to R17

**Comment by asachs01** [comment]
One note here that may complicate things: Any users who are running CentOS/RHEL are going to be pulling in 16B03 in via Epel. We may need to update the docs to point to using something like the [Erlang Solutions repos](https://www.erlang-solutions.com/resources/download.html) (which will also require the [compatibility shim repo](https://github.com/jasonmcintosh/esl-erlang-compat)). Alternatively, we could bump up support to at least 18.X, which for our CentOS/RHEL users, would be one less package to install, since Rabbit has that in their  @[zero-dependency](https://github.com/rabbitmq/erlang-rpm) repo.

**Comment by cwjohnston** [comment]
This issue was moved to sensu/sensu-docs-site#118
