### ISSUE TITLE
sensu xmail configuration question

### ISSUE THREAD

**Issue by downright770** [sensu/sensu-docs#628]
Hi,
I'm still getting use to Sensu and wanted to setup a email to Jira ticket.
In Jira we have a hook to email that is already accepting emails from cmdline and creating 
tickets. 
I tried to follow how to set this up on sensu using mailx but can't get anywhere with it.
What is the easiest way to do this using mailx. 
Do i need a filter setting for my subscriptions . 
Any help in understanding this would be great.

**Comment by mbbroberg** [comment]
Hey @downright770! I'm so glad you're getting up and running with Sensu. We would love to help you, though an issue on this Repo is not the right place for that. 

* If you want real-time help from peers, [join us on Slack](http://slack.sensu.io)
* If you'd prefer email, email the [Sensu Users mailing list](https://groups.google.com/forum/#!forum/sensu-users)
* If you're a Sensu Enterprise user, you have [fantastic support](https://sensuapp.org/support) through [Account Manager](https://account.sensuapp.com/)

Please hop in on any of these channels and let's figure it out together! Closing this issue since it's not related to the repo. Cheers.
