### ISSUE TITLE
Check reference for 2.x is incorrect for check_hooks

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-docs#678]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [x] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior

I'd expect the sensu 2.x docs for a check's `check_hooks` to match what is output with JSON when listing a check.

## Current Behavior

Current docs show `check_hooks` as an array of hooks when it's actually much more structured data:

```
"check_hooks": [
      {
        "critical": [
          "test"
        ]
      }
    ],
```

## Steps to Reproduce (for bugs)

https://docs.sensu.io/sensu-core/2.0/reference/checks/#check-attributes

## Context

I am working with @ghoneycutt to automate sensu 2.x with Puppet and was basing Puppet code off the reference which appears to be incorrect in this case.

* Browser(s) and version(s): Chrome 67
* OS: OS X 10.11

**Comment by echlebek** [comment]
Before correcting this documentation, let's do a review of the feature and decided whether it should function in the way the docs describe, or whether the docs should describe how it currently works.

**Comment by nikkictl** [comment]
Sorry for the confusion here! Yes, hooks behave a little differently than resources like handlers for example. A check can have a list of handler names ex. `"handlers": ["pagerduty", "email"]`. However hooks must have a `type` associated with them in order to determine if they should execute based on the check status. For this reason, they are mapped like this:
```
"check_hooks": [
  {
    "0": [
      "passing-hook","always-run-this-hook"
    ]
  },
  {
    "critical": [
      "failing-hook","collect-diagnostics","always-run-this-hook"
    ]
  }
]
```
The hook type can be 0-255 or any of these [severities](https://github.com/sensu/sensu-go/blob/f0e843460f254430460ccb634296387f3fb59e9d/types/hook.go#L20). We should update this in our docs so it matches the current implementation 👍
