### ISSUE TITLE
Spec and size tasks for usable legacy documentation

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-docs#91]
The previous Sensu documentation project (https://github.com/sensu/sensu-docs) can run independently as a middleman site on Heroku. This site can provide legacy documentation for older Sensu versions (< 0.29). We can use a subdomain like "legacy-docs.sensu.io" and setup the appropriate redirects.

While the middleman site can run as is, it lack the CSS/stylization that the Sensu website currently provides it. We must port over the necessary CSS/javascript from the website project (https://github.com/sensu/website).

**Comment by cwjohnston** [comment]
After further discussion with @grepory and @mbbroberg, we've determined this issue needs some refining to better determine the size/scope of what we want to achieve. As such, we're repurposing this issue.

By the time we reach soft launch milestone, we should have identified and correctly sized tasks for making legacy documentation usable independent of the primary docs site.

**Comment by calebhailey** [comment]
It seems to me that this issue should be rephrased as "what should we do with Sensu version 0.24 => 0.28 documentation?", since we are already not hosting documentation for Sensu versions <0.24. I'm of the opinion that we don't need to _host_ legacy docs for all eternity as long as we continue to make them available in some capacity. At the very least it seems to me that this issue shouldn't hold up the soft launch and should potentially be removed from the milestone. 

Discuss!

**Comment by cwjohnston** [comment]
You're right Caleb, we're not going to make this gating. As members of the Sensu community have largely agreed to support versions 0.29 and newer, or otherwise encourage folks on older versions of Sensu to make the upgrade, folks are welcome to open an issue against sensu/sensu-docs if they have a need to see this legacy content stylized.
